<?php
# This file was automatically generated by the MediaWiki 1.36.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

$mwMode = getenv( 'MW_MODE' ) ?: 'production';
$mwIsDev = $mwMode === 'dev';

if ( $mwIsDev ) {
	error_reporting( -1 );
	ini_set( 'display_errors', 1 );
	$wgShowExceptionDetails = true;
	$wgDebugDumpSql = true;
	$wgDebugComments = true;
} else {
	$wgShowExceptionDetails = false;
	$wgDebugDumpSql = false;
	$wgDebugComments = false;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "NeoWiki Demo";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = '/w';
$wgArticlePath = "/wiki/$1";
$wgUsePathInfo = true;

## Pretty URLs for the NeoWiki Data tab: /wiki/PageName/subjects
$wgActionPaths['subjects'] = "/wiki/$1/subjects";

## The protocol and server name to use in fully-qualified URLs
$wgServer = getenv( 'MW_SERVER' );

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/wiki.png" ];
$wgFavicon = "$wgScriptPath/images/favicon.ico";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = getenv( 'MW_MAIL' );
$wgPasswordSender = getenv( 'MW_MAIL' );

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = false;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = ( getenv( 'MARIADB_HOST' ) ?: 'db' ) . ':' . ( getenv( 'MARIADB_PORT' ) ?: '3306' );
$wgDBname = getenv( 'MARIADB_DATABASE' );
$wgDBuser = getenv( 'MARIADB_USER' );
$wgDBpassword = getenv( 'MARIADB_PASSWORD' );

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
//$wgMainCacheType = 'redis';
//$wgSessionCacheType = 'redis';
//$wgMemCachedServers = [];
//$wgObjectCaches['redis'] = [
//    'class' => 'RedisBagOStuff',
//    'servers' => [ 'redis:6379' ]
//];
//$wgJobTypeConf['default'] = [
//    'class' => 'JobQueueRedis',
//    'redisServer' => 'redis:6379',
//    'redisConfig' => [],
//    'claimTTL' => 3600,
//    'daemonized' => true
//];

if ( $mwIsDev ) {
	$wgMainCacheType = CACHE_NONE;
	$wgMessageCacheType = CACHE_NONE;
	$wgLanguageConverterCacheType = CACHE_NONE;
	$wgSessionCacheType = CACHE_DB;
	$wgParserCacheType = CACHE_NONE;
} else {
	$wgMainCacheType = CACHE_ACCEL;
	$wgMessageCacheType = CACHE_ACCEL;
	$wgLanguageConverterCacheType = CACHE_ACCEL;
	$wgSessionCacheType = CACHE_DB;
	$wgParserCacheType = CACHE_ACCEL;
}
$wgRevisionCacheExpiry = 0;
$wgUseLocalMessageCache = true;

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale. This should ideally be set to an English
## language locale so that the behaviour of C library functions will
## be consistent with typical installations. Use $wgLanguageCode to
## localise the wiki.
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

$wgSecretKey = getenv( 'MW_TOKEN' );;

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
# $wgUpgradeKey = "be55e528a693624f";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Namespace settings

# Set meta namespace
$wgMetaNamespace = 'Wiki';

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector-2022";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );


# End of automatically generated settings.
# Add more configuration options below.

wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'ParserFunctions' );

// Empty MW_SMTP_HOST means "no SMTP at all": the dev stack sets it when the
// mailcatcher service is deselected. Unset means "use the mode's default".
$mwSmtpHost = getenv( 'MW_SMTP_HOST' );
$wgSMTP = [];
if ( $mwIsDev && $mwSmtpHost === false ) {
	// Default to the mailcatcher sidecar in dev mode.
	$wgSMTP = [ 'host' => 'mailcatcher', 'port' => 1025 ];
} elseif ( $mwSmtpHost !== false && $mwSmtpHost !== '' ) {
	$wgSMTP = [
		'host' => getenv( 'MW_SMTP_HOST' ),
		'IDHost' => getenv( 'MW_SMTP_ID_HOST' ),
		'port' => (int)getenv( 'MW_SMTP_PORT' ),
	];

	if ( getenv( 'MW_SMTP_USER' ) !== false ) {
		$wgSMTP['auth'] = true;
		$wgSMTP['username'] = getenv( 'MW_SMTP_USER' );
		$wgSMTP['password'] = getenv( 'MW_SMTP_PASSWORD' );
	}
}

if ( getenv( 'MW_PASSWORD_SENDER' ) !== false ) {
    $wgPasswordSender = getenv( 'MW_PASSWORD_SENDER' );
}

wfLoadExtension( 'NeoWiki' );
wfLoadExtension( 'RedHerb', "$IP/extensions/NeoWiki/tests/RedHerb/extension.json" );

$wgNeoWikiEnableDevelopmentUI = true;

$neo4jScheme = getenv( 'NEO4J_SCHEME' ) ?: 'bolt';
$neo4jAddress = ( getenv( 'NEO4J_HOST' ) ?: 'neo' ) . ':' . ( getenv( 'NEO4J_PORT' ) ?: '7687' );

$wgNeoWikiNeo4jInternalWriteUrl = $neo4jScheme . '://' . getenv( 'NEO4J_USERNAME' ) . ':' . getenv( 'NEO4J_PASSWORD' ) . '@' . $neo4jAddress;
$wgNeoWikiNeo4jInternalReadUrl = $neo4jScheme . '://' . getenv( 'NEO4J_USERNAME_READ' ) . ':' . getenv( 'NEO4J_PASSWORD_READ' ) . '@' . $neo4jAddress;

// SPARQL graph store (QLever) for the SPARQL projection plugin (#586). Both the demo stack and the
// dev stack run the qlever service defined in docker-compose.yml by default and point the wiki at
// its endpoint via QLEVER_URL. A non-empty value is the gate: an image started outside those stacks
// gets QLEVER_URL unset rather than a configuration pointing at a host that does not exist, and so
// does CI, whose docker-compose.ci.yml replaces that file and sets neither variable. The dev stack's
// Makefile sets it to the empty string when `services=` deselects qlever, which disables the
// configuration the same way. The access token is an ordinary optional credential, defaulted in the
// compose file so a Docker/.env written before it existed still yields a working store. Skipped
// under PHPUnit so integration tests never post updates here — they configure their own stores with
// mocked HTTP via overrideConfigValue(), so the default must stay empty during tests.
//
// Two entries, one endpoint: the native projection and the EDM projection of the demo data's
// Mapping:EDM page are kept in the same QLever index as sibling projections. Each lands in its own
// family of per-page named graphs (#1053), so neither overwrites the other. The query surfaces
// target the first entry's endpoint, which both entries share, so a query reaches both projections.
$qleverUrl = getenv( 'QLEVER_URL' );

if ( $qleverUrl !== false && $qleverUrl !== '' && !defined( 'MW_PHPUNIT_TEST' ) ) {
	$wgNeoWikiSparqlStores = [
		[
			'updateUrl' => $qleverUrl,
			'accessToken' => getenv( 'QLEVER_ACCESS_TOKEN' ) ?: null,
			'projection' => 'native',
		],
		[
			'updateUrl' => $qleverUrl,
			'accessToken' => getenv( 'QLEVER_ACCESS_TOKEN' ) ?: null,
			'projection' => 'EDM',
		],
	];
}

// Allow anonymous REST API calls on the wiki.
$wgCrossSiteAJAXdomains = [
	'*'
];

// Expose MediaWiki core's OpenAPI spec endpoints (T365753) so the
// auto-generated NeoWiki REST spec is reachable at
// /rest.php/specs/v0/module/- and /rest.php/specs/v0/discovery.
$wgRestAPIAdditionalRouteFiles[] = 'includes/Rest/specs.v0.json';

$wgEmailConfirmToEdit = false;

$wgGroupPermissions['*']['edit'] = false;

$wgUseRCPatrol = false;
$wgUseNPPatrol = false;

# Per-worktree opt-in overrides (gitignored). Use to load sister extensions for integration
# work, set custom debug toggles, or override hooks.
$mwLocal = __DIR__ . '/LocalSettings.local.php';
if ( file_exists( $mwLocal ) ) {
	require_once $mwLocal;
}
