{{- if .Values.mariadb.enabled }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: {{ include "neowiki.mariadb.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "neowiki.mariadb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  image: {{ .Values.mariadb.image | quote }}
  rootPasswordSecretKeyRef:
    name: {{ include "neowiki.mariadb.secret.name" . }}
    key: MARIADB_ROOT_PASSWORD
  storage:
    size: {{ .Values.mariadb.storage.size | quote }}
    {{- if .Values.mariadb.storage.storageClassName }}
    storageClassName: {{ .Values.mariadb.storage.storageClassName | quote }}
    {{- end }}
  replicas: {{ .Values.mariadb.replicas }}
  databases:
    - name: {{ .Values.mariadb.auth.database | quote }}
      characterSet: {{ default "utf8mb4" .Values.mariadb.characterSet | quote }}
      collate: {{ default "utf8mb4_unicode_ci" .Values.mariadb.collate | quote }}
  users:
    - name: {{ .Values.mariadb.auth.username | quote }}
      passwordSecretKeyRef:
        name: {{ include "neowiki.mariadb.secret.name" . }}
        key: MARIADB_PASSWORD
      host: "%"
  cleanupPolicy: Delete
{{- end }}