apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neowiki.mariadb.secret.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "neowiki.mariadb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
{{- if .Values.mariadb.enabled }}
  MARIADB_ROOT_PASSWORD: {{ required "mariadb.auth.rootPassword is required" .Values.mariadb.auth.rootPassword | quote }}
{{- end }}
  MARIADB_PASSWORD: {{ ternary .Values.externalDatabase.password .Values.mariadb.auth.password .Values.externalDatabase.enabled | required "mariadb.auth.password or externalDatabase.password is required" | quote }}