{{- if and .Values.neo4j.enabled (not .Values.externalNeo4j.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neowiki.neo4j.readAuthSecret.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "neowiki.neo4j.readAuthSecret.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  NEO4J_USERNAME_READ: {{ required "neo4j.neo4j.readUser is required" .Values.neo4j.neo4j.readUser | quote }}
  NEO4J_PASSWORD_READ: {{ required "neo4j.neo4j.readPassword is required" .Values.neo4j.neo4j.readPassword | quote }}
{{- end }}
